# Generated by Django 5.1.1 on 2024-09-08 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_category_product_delete_moodentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
